apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: devops-demo-app
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: devops-demo

images:
  - name: devops-demo-app
    newName: ghcr.io/your-org/devops-demo-app
    newTag: latest