apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: devops-demo-app
  labels:
    app.kubernetes.io/name: devops-demo-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-demo-app