apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-demo-app
  labels:
    app.kubernetes.io/name: devops-demo-app
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-demo-app
  labels:
    app.kubernetes.io/name: devops-demo-app
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-demo-app
  labels:
    app.kubernetes.io/name: devops-demo-app
subjects:
- kind: ServiceAccount
  name: devops-demo-app
roleRef:
  kind: Role
  name: devops-demo-app
  apiGroup: rbac.authorization.k8s.io