apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

namePrefix: staging-

commonLabels:
  environment: staging

images:
  - name: devops-demo-app
    newTag: main