apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-demo
  namespace: argocd
  labels:
    app.kubernetes.io/name: devops-demo
spec:
  description: DevOps Demo Application Project
  
  # Source repositories
  sourceRepos:
  - 'https://github.com/your-org/devops-demo.git'
  - 'https://charts.bitnami.com/bitnami'
  - 'https://prometheus-community.github.io/helm-charts'
  
  # Destination clusters and namespaces
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  - namespace: staging
    server: https://kubernetes.default.svc
  - namespace: production
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  
  # Cluster resource whitelist
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'admissionregistration.k8s.io'
    kind: MutatingWebhookConfiguration
  - group: 'admissionregistration.k8s.io'
    kind: ValidatingWebhookConfiguration
  
  # Namespace resource whitelist
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: ServiceAccount
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: ReplicaSet
  - group: 'apps'
    kind: StatefulSet
  - group: 'apps'
    kind: DaemonSet
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  - group: 'autoscaling'
    kind: HorizontalPodAutoscaler
  - group: 'policy'
    kind: PodDisruptionBudget
  - group: 'rbac.authorization.k8s.io'
    kind: Role
  - group: 'rbac.authorization.k8s.io'
    kind: RoleBinding
  - group: 'monitoring.coreos.com'
    kind: ServiceMonitor
  - group: 'monitoring.coreos.com'
    kind: PrometheusRule
  
  # Roles for project members
  roles:
  - name: admin
    description: Admin privileges for DevOps Demo project
    policies:
    - p, proj:devops-demo:admin, applications, *, devops-demo/*, allow
    - p, proj:devops-demo:admin, repositories, *, *, allow
    - p, proj:devops-demo:admin, clusters, *, *, allow
    groups:
    - devops-team
    
  - name: developer
    description: Developer access to development environment
    policies:
    - p, proj:devops-demo:developer, applications, get, devops-demo/*, allow
    - p, proj:devops-demo:developer, applications, sync, devops-demo/dev-*, allow
    - p, proj:devops-demo:developer, applications, action/*, devops-demo/dev-*, allow
    groups:
    - developers
    
  - name: reviewer
    description: Read-only access for reviewers
    policies:
    - p, proj:devops-demo:reviewer, applications, get, devops-demo/*, allow
    - p, proj:devops-demo:reviewer, repositories, get, *, allow
    groups:
    - reviewers