apiVersion: v2
name: devops-demo-app
description: A Helm chart for the DevOps Demo Application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - api
  - fastapi
  - python
  - demo
home: https://github.com/your-org/devops-demo
sources:
  - https://github.com/your-org/devops-demo
maintainers:
  - name: DevOps Team
    email: devops@example.com