apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: devops-demo
    app.kubernetes.io/environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devops-demo
  
  source:
    repoURL: https://github.com/your-org/devops-demo.git
    targetRevision: main
    path: helm/charts/app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: latest
        - name: environment
          value: production
        - name: replicaCount
          value: "5"
        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts[0].host
          value: api.example.com
        - name: ingress.tls[0].secretName
          value: api-tls
        - name: ingress.tls[0].hosts[0]
          value: api.example.com
        - name: resources.requests.cpu
          value: "200m"
        - name: resources.requests.memory
          value: "512Mi"
        - name: resources.limits.cpu
          value: "1000m"
        - name: resources.limits.memory
          value: "1Gi"
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "5"
        - name: autoscaling.maxReplicas
          value: "20"
        - name: blueGreen.enabled
          value: "true"
        - name: podDisruptionBudget.enabled
          value: "true"
        - name: podDisruptionBudget.minAvailable
          value: "3"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  
  syncPolicy:
    # Manual sync for production with strict controls
    automated: null
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 2
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  
  revisionHistoryLimit: 15
  
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    jsonPointers:
    - /spec/targetCPUUtilizationPercentage
    - /spec/metrics
  
  info:
  - name: Description
    value: DevOps Demo Application - Production Environment
  - name: Owner
    value: DevOps Team
  - name: Environment
    value: Production
  - name: DeploymentStrategy
    value: Blue-Green
  - name: SLA
    value: 99.9% uptime