apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

namePrefix: prod-

commonLabels:
  environment: production

images:
  - name: devops-demo-app
    newTag: latest